version: '3'
services:
  frontend:
    container_name: front-production
    image: snare/frontend-crud:v1
    ports:
      - "3308:2000"
    expose:
      - "3308"
    networks:
      - produccion
  mysql:
    container_name: db-production
    image: mysql:8.0
    ports:
      - "3307:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: '1212'
      MYSQL_DATABASE: dbcontrolescolar
    volumes:
      - ./BD/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - produccion
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 15s
            retries: 10
  backend:
    container_name: back-production
    image: snare/backend-crud:v1
    ports:
      - "4000:4000"
    expose:
      - "4000"
    networks:
      - produccion
    depends_on:
      mysql:
        condition: service_healthy
networks:
  produccion:
    driver: bridge
